# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "my-express-app.fullname" . }}
#   labels:
#     app: {{ include "my-express-app.name" . }}
# spec:
#   type: {{ .Values.service.type }}
#   selector:
#     app: {{ include "my-express-app.name" . }}
#   ports:
#     - protocol: TCP
#       port: {{ .Values.service.port }}
#       targetPort: {{ .Values.service.targetPort }}
#       nodePort: {{ .Values.service.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-express-app.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "my-express-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}       # 80
      targetPort: {{ .Values.service.targetPort }} # 8080

