apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "my-express-app.fullname" . }}-backendconfig
spec:
  healthCheck:
    requestPath: {{ .Values.backendConfig.healthCheckPath }}
    port: {{ .Values.backendConfig.port }}
