apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-express-app.fullname" . }}
  annotations:
    # Required for GCE Ingress (NEG)
    cloud.google.com/neg: '{"ingress": true}'

    # ðŸ”´ THIS is what was missing (attach BackendConfig)
    {{- if .Values.backendConfig.enabled }}
    cloud.google.com/backend-config: |
      {"default":"{{ include "my-express-app.fullname" . }}-backendconfig"}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "my-express-app.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}        # 80
      targetPort: {{ .Values.service.targetPort }} # 8080
